import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="mx-auto max-w-3xl px-6 lg:max-w-6xl lg:px-8">
        <Header />
        <main className="relative pb-16 bg-gray-100">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
