import type { Metadata } from "next";
import { cx } from "../utils";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chovlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={cx(
          "mx-auto max-w-3xl px-6 lg:max-w-6xl lg:px-8 bg-light dark:bg-dark"
        )}
      >
        <Header />
        <main className="relative pb-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
